### ISSUE TITLE
How to remove the number of slides from the video?

### ISSUE THREAD

**Issue by SaraMorsy** [jhudsl/ariExtra#1]
Hi,

I tried this amazing package and all goes well except in the video, the number of slides is mentioned. I checked the notes and found that it is automatically added to the notes. how to remove it?
Here is my code 

```{r}
library(ariExtra)
library(docxtractr)
pptx = "E:/ari/ari/DM.pptx"
pdf = convert_to_pdf(pptx) # >= 0.6.2 
pngs = pdf_convert(pdf, dpi = 100)
notes = pptx_slide_note_df(pptx)
pptx_result = ari_spin(pngs, notes, output = "pptx.mp4", voice = "Amy",
                                            divisible_height = TRUE, subtitles = TRUE,video_sync_method = "1",fast_start=F)
```

Session info
R version 4.1.1 (2021-08-10)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows 10 x64 (build 17134)

Matrix products: default

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] ari_0.3.5        aws.polly_0.1.5  docxtractr_0.6.5 ariExtra_0.3.1  

loaded via a namespace (and not attached):
 [1] Rcpp_1.0.7          pillar_1.6.2        compiler_4.1.1      base64enc_0.1-3    
 [5] prettyunits_1.1.1   pdftools_3.0.1      tools_4.1.1         progress_1.2.2     
 [9] digest_0.6.27       jsonlite_1.7.2      evaluate_0.14       lifecycle_1.0.0    
[13] tibble_3.1.4        pkgconfig_2.0.3     rlang_0.4.11        curl_4.3.2         
[17] yaml_2.2.1          xfun_0.26           fastmap_1.1.0       dplyr_1.0.7        
[21] httr_1.4.2          xml2_1.3.2          knitr_1.34          generics_0.1.0     
[25] vctrs_0.3.8         askpass_1.1         hms_1.1.1           webshot_0.5.2      
[29] tidyselect_1.1.1    glue_1.4.2          qpdf_1.1            R6_2.5.1           
[33] fansi_0.5.0         rmarkdown_2.11      tuneR_1.3.3.1       purrr_0.3.4        
[37] magrittr_2.0.1      MASS_7.3-54         ellipsis_0.3.2      htmltools_0.5.2    
[41] rvest_1.0.1         aws.signature_0.6.0 text2speech_0.2.13  utf8_1.2.2         
[45] tinytex_0.33        signal_0.7-7        crayon_1.4.1

**Comment by muschellij2** [comment]
Can you send a copy of the pptx?  Or at least print out the output of `notes`

**Comment by SaraMorsy** [comment]
I printed the notes and they have the slide number at the end of each line. I changed it manually but I want it to be automatically 
Here is the PowerPoint
https://docs.google.com/presentation/d/1IYaTez-LctWW9EFEvggY8_TV7AXWy2-X/edit?usp=sharing&ouid=110464404064737002824&rtpof=true&sd=true

**Comment by muschellij2** [comment]
Dev version should work:
``` r
library(ariExtra)
pptx_notes("~/tmp/DM2.pptx")
#> Warning in dir.create(props_dir, recursive = TRUE):
#> '/tmp/RtmpTIGfge/file6ae07ac6945e/docProps' already exists
#>                                                                                                                                                                                                                                                                                                                                                                                         notesSlide1.xml 
#>                                                                                                                                                                                                                                                                                                   "Welcome to our course, in this video, we are going to explain  Cardiovascular problems and COVID-19" 
#>                                                                                                                                                                                                                                                                                                                                                                                         notesSlide2.xml 
#>                                                                                                                                                                                                                                                           "The spike or S glycoprotein is a transmembrane protein with a molecular weight of about 150  kDa  found in the outer portion of the virus. " 
#>                                                                                                                                                                                                                                                                                                                                                                                         notesSlide3.xml 
#> "The nucleocapsid known as N protein is the structural component of  CoV  localizing in the endoplasmic reticulum-Golgi region that structurally is bound to the nucleic acid material of the virus. Because the protein is bound to RNA, the protein is involved in processes related to the viral genome, the viral replication cycle, and the cellular response of host cells to viral infections. "
```

<sup>Created on 2021-12-08 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1)</sup>

**Comment by SaraMorsy** [comment]
Thank you, it worked
